import { EmailValidator } from "@angular/forms";

export interface Employee{
  employeeID : string,
  initials: string,
  firstName: string,
  lastName: string,
  title: string,
  gender: string,
  dateOfBirth: Date,
  employeeCategory: string,
  leaveAct: string,
  designation: string,
  department: string,
  salaryType: string,
  amount: string,
  joinedOn: Date,
  otherNames: string,
  emailID: EmailValidator,
  nic: string,
  nationality: string,
  religion: string,
  passportNo: string,
  licenseNo: string,
  bloodGroup: string,
  policeStation: string,
  district: string,
  profileImg: any,
  EPFNo: string,
  empGrade:string,
  empType: string,
  startDate: Date,
  endDate: Date,
  occuClassi: string,
  advance: string
}
